### ISSUE TITLE
Incorrect parser options for TypeScript setup

### ISSUE THREAD

**Issue by bertdeblock** [Bagaar/eslint-config#3]
Defined here:
https://github.com/Bagaar/eslint-config/blob/master/lib/base.js#L10-L19

Only `ecmaVersion: 'latest'` is needed I think.

**Comment by gvdp** [comment]
Removed those unnecessary options

**Comment by bertdeblock** [comment]
Those are still needed when using the `@babel/eslint-parser` parser.
