### ISSUE TITLE
Configure `no-console` rule consistently or remove altogether

### ISSUE THREAD

**Issue by bertdeblock** [Bagaar/eslint-config#4]
I would prefer it to be configured consistently or not at all (allow everything).
I don't think we should allow only `warn` and `error` in app code, and then allow everything in `tests/dummy/**`.

**Comment by gvdp** [comment]
Removed the override in `tests/dummy/**` , not sure why it was there, don't think we should allow console logs there either.

**Comment by bertdeblock** [comment]
Why do we only allow `error` and `warn`. Why not `info`, `debug`, `table`, ...?
