### ISSUE TITLE
Why are `no-undef` and `no-unused-vars` turned off in TS projects?

### ISSUE THREAD

**Issue by bertdeblock** [Bagaar/eslint-config#9]

**Comment by gvdp** [comment]
It's only in the interface files. In the Novalet project we have interfaces defined which are not exported but still used, these then gave linting errors. But probably the Typescript setup there is not really correct then. Turning this rule of for interface files is not ideal but also not too bad.

**Comment by bertdeblock** [comment]
Can you link to some examples?
